version: '3.8'

services:
  #PostgreSQL Service
  postgres:
    image: postgres:13
    container_name: set_sail_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB Service
  mongo:
    image: mongo:4.4
    container_name: set_sail_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Node.js Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: set_sail_backend
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_URI: mongodb://mongo:27017/set_sail
    depends_on:
      - postgres
      - mongo

volumes:
  postgres_data:
  mongo_data: